
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - images_data:/app/images_data
    environment:
      FLASK_ENV: development
      UNSPLASH_API_KEY: ${UNSPLASH_API_KEY}

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      CHOKIDAR_USEPOLLING: "true"

volumes:
  images_data: